name: Deploy green-dev to prod

on: [workflow_dispatch]

jobs:
  deploy-prod:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: "green-dev"
      - name: Run deployment
        run: ./deploy-prod.sh
        env:
          HEROKU_API_KEY: "${{ secrets.HEROKU_API_KEY }}"
      - name: Tag successful deployment
        run: |
          function force_push_tag {
            local -r tag="$1"
            git tag "$tag"
            git push --force origin "refs/tags/$tag:refs/tags/$tag"
          }
          force_push_tag "green-prod-$( date +"%Y%m%d%H%M%S" )"
          force_push_tag "green-prod"
