name: Deploy master to dev

on:
  push:
    branches:
      - master

jobs:
  deploy-dev:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run deployment
        run: ./deploy-dev.sh
      - name: Tag successful deployment
        run: |
          git tag "green-dev-$( date +"%Y%m%d%H%M%S" )"
          git tag "green-dev"
          git push --tags
