name: Deploy master to dev

on:
  push:
    branches:
      - master

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run deployment
        run: ./deploy-dev.sh
