name: Deploy master to dev
concurrency: deploy-dev

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run deployment
        run: ./deploy-dev.sh
        env:
          HEROKU_API_KEY: "${{ secrets.HEROKU_API_KEY }}"
      - name: Tag successful deployment
        run: |
          function force_push_tag {
            local -r tag="$1"
            git tag --force "$tag"
            git push --force origin "refs/tags/$tag:refs/tags/$tag"
          }
          force_push_tag "green-dev-$( date +"%Y%m%d%H%M%S" )"
          force_push_tag "green-dev"
