name: Deploy green-qa to prod
concurrency: deploy-prod

on:
  workflow_dispatch:
    inputs:
      name: "is_dispatch"
      required: false
      default: true
  workflow_run:
    workflows: ["Deploy green-dev to qa"]
    types: [completed]

jobs:
  deploy:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.inputs.dispatch }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: "green-qa"
      - name: Run deployment
        run: ./deploy-prod.sh
        env:
          HEROKU_API_KEY: "${{ secrets.HEROKU_API_KEY }}"
      - name: Tag successful deployment
        run: |
          function force_push_tag {
            local -r tag="$1"
            git tag --force "$tag"
            git push --force origin "refs/tags/$tag:refs/tags/$tag"
          }
          force_push_tag "green-prod-$( date +"%Y%m%d%H%M%S" )"
          force_push_tag "green-prod"
